# Generated by Django 5.0.1 on 2024-01-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='title',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
